import type { Config } from "./generator";

export function buildActionsMatrix(c: Config): string {
  const nodeVersions = c.features.find(f => f.id === 'node')?.versions || ['20'];
  const osList = ['ubuntu-latest'];
  
  // Add macOS and Windows if cross-platform testing is needed
  const includePlatforms = [
    { os: 'ubuntu-latest', label: 'Linux' },
    { os: 'macos-latest', label: 'macOS' },
    { os: 'windows-latest', label: 'Windows' },
  ];

  return `# ─────────────────────────────────────────────────────────────────────
# Multi-platform CI Matrix for ${c.owner}/${c.repo}
# Generated by GHCR Devcontainer Forge
# ─────────────────────────────────────────────────────────────────────

name: Multi-Platform CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  workflow_dispatch:

jobs:
  test:
    name: Test on \${{ matrix.os }} (Node \${{ matrix.node-version }})
    runs-on: \${{ matrix.os }}
    
    strategy:
      fail-fast: false
      matrix:
        os: [${osList.map(os => `'${os}'`).join(', ')}]
        node-version: [${nodeVersions.map(v => `'${v}'`).join(', ')}]
        include:
${includePlatforms.map(p => `          - os: '${p.os}'
            platform: '${p.label}'`).join('\n')}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js \${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: \${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint
        continue-on-error: \${{ matrix.os == 'windows-latest' }}

      - name: Run type check
        run: npm run typecheck
        continue-on-error: \${{ matrix.os == 'windows-latest' }}

      - name: Run tests
        run: npm test
        env:
          CI: true

      - name: Run tests with coverage
        if: matrix.os == 'ubuntu-latest' && matrix.node-version == '${nodeVersions[0]}'
        run: npm run test:coverage

      - name: Upload coverage to Codecov
        if: matrix.os == 'ubuntu-latest' && matrix.node-version == '${nodeVersions[0]}'
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage/lcov.xml
          flags: \${{ matrix.platform }}
          fail_ci_if_error: false

      - name: Build application
        run: npm run build

      - name: Upload build artifacts
        if: matrix.os == 'ubuntu-latest' && matrix.node-version == '${nodeVersions[0]}'
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: dist/
          retention-days: 7

  e2e:
    name: E2E Tests on \${{ matrix.browser }}
    needs: test
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        browser: [chromium, firefox, webkit]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '${nodeVersions[0]}'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps \${{ matrix.browser }}

      - name: Build application
        run: npm run build

      - name: Run E2E tests
        run: npx playwright test --project=\${{ matrix.browser }}
        env:
          CI: true

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report-\${{ matrix.browser }}
          path: playwright-report/
          retention-days: 7

  security:
    name: Security Audit
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '${nodeVersions[0]}'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run npm audit
        run: npm audit --audit-level=moderate
        continue-on-error: true

      - name: Run Snyk security scan
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: \${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload Trivy results to GitHub Security
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'

  performance:
    name: Performance Tests
    needs: test
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '${nodeVersions[0]}'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build

      - name: Run Lighthouse CI
        uses: treosh/lighthouse-ci-action@v10
        with:
          urls: |
            http://localhost:${c.ports[0] || '3000'}
          uploadArtifacts: true
          temporaryPublicStorage: true

  deploy-preview:
    name: Deploy Preview
    needs: [test, e2e]
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '${nodeVersions[0]}'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build

      - name: Deploy to Vercel Preview
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: \${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: \${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: \${{ secrets.VERCEL_PROJECT_ID }}
          github-token: \${{ secrets.GITHUB_TOKEN }}
          scope: \${{ secrets.VERCEL_ORG_ID }}
`;
}
