import type { Config } from "./generator";

export function buildDockerCompose(c: Config): string {
  const services: Record<string, any> = {};
  
  // Main application service
  services[c.repo.toLowerCase()] = {
    build: {
      context: ".",
      dockerfile: ".devcontainer/Dockerfile",
    },
    volumes: ["..:/workspace:cached"],
    command: "sleep infinity",
    environment: {
      NODE_ENV: "development",
    },
  };

  // Add PostgreSQL if in ports
  if (c.ports.includes("5432")) {
    services.postgres = {
      image: "postgres:16-alpine",
      environment: {
        POSTGRES_USER: "postgres",
        POSTGRES_PASSWORD: "postgres",
        POSTGRES_DB: c.repo.toLowerCase(),
      },
      ports: ["5432:5432"],
      volumes: ["postgres-data:/var/lib/postgresql/data"],
    };
  }

  // Add Redis if in ports
  if (c.ports.includes("6379")) {
    services.redis = {
      image: "redis:7-alpine",
      ports: ["6379:6379"],
      volumes: ["redis-data:/data"],
    };
  }

  // Add MongoDB if in ports
  if (c.ports.includes("27017")) {
    services.mongodb = {
      image: "mongo:7",
      ports: ["27017:27017"],
      volumes: ["mongo-data:/data/db"],
    };
  }

  // Add MySQL if in ports
  if (c.ports.includes("3306")) {
    services.mysql = {
      image: "mysql:8",
      environment: {
        MYSQL_ROOT_PASSWORD: "root",
        MYSQL_DATABASE: c.repo.toLowerCase(),
      },
      ports: ["3306:3306"],
      volumes: ["mysql-data:/var/lib/mysql"],
    };
  }

  // Add Elasticsearch if in ports
  if (c.ports.includes("9200")) {
    services.elasticsearch = {
      image: "elasticsearch:8.11.0",
      environment: {
        discovery: { type: "single-node" },
        "xpack.security.enabled": "false",
      },
      ports: ["9200:9200"],
      volumes: ["es-data:/usr/share/elasticsearch/data"],
    };
  }

  const compose = {
    version: "3.8",
    services,
    volumes: Object.keys(services).reduce((acc, key) => {
      if (key === "postgres") acc["postgres-data"] = undefined;
      if (key === "redis") acc["redis-data"] = undefined;
      if (key === "mongodb") acc["mongo-data"] = undefined;
      if (key === "mysql") acc["mysql-data"] = undefined;
      if (key === "elasticsearch") acc["es-data"] = undefined;
      return acc;
    }, {} as Record<string, any>),
  };

  return `# Docker Compose for ${c.owner}/${c.repo}
# Generated by GHCR Devcontainer Forge
# Usage: docker-compose up -d

${JSON.stringify(compose, null, 2)}
`;
}
