import type { Config } from "./generator";

export function buildEnvExample(c: Config): string {
  const hasPostgres = c.ports.includes("5432");
  const hasRedis = c.ports.includes("6379");
  const hasMongo = c.ports.includes("27017");
  const hasMysql = c.ports.includes("3306");
  const hasElastic = c.ports.includes("9200");

  const lines: string[] = [
    `# ─────────────────────────────────────────────────────────────────────`,
    `# Environment Variables for ${c.owner}/${c.repo}`,
    `# Generated by GHCR Devcontainer Forge`,
    `# Copy this file to .env and fill in the values`,
    `# ─────────────────────────────────────────────────────────────────────`,
    ``,
    `# ── Application ─────────────────────────────────────────────────────`,
    `NODE_ENV=development`,
    `PORT=${c.ports[0] || '3000'}`,
    `HOST=0.0.0.0`,
    `LOG_LEVEL=debug`,
    ``,
    `# ── Authentication ──────────────────────────────────────────────────`,
    `JWT_SECRET=change-me-to-a-random-string`,
    `SESSION_SECRET=change-me-to-another-random-string`,
    ``,
    `# ── API Keys ────────────────────────────────────────────────────────`,
    `# Add your API keys here`,
    `# OPENAI_API_KEY=sk-...`,
    `# GITHUB_TOKEN=ghp_...`,
    ``,
  ];

  if (hasPostgres) {
    lines.push(
      `# ── PostgreSQL ──────────────────────────────────────────────────────`,
      `DATABASE_URL=postgresql://postgres:postgres@localhost:5432/${c.repo.toLowerCase()}`,
      `POSTGRES_HOST=localhost`,
      `POSTGRES_PORT=5432`,
      `POSTGRES_USER=postgres`,
      `POSTGRES_PASSWORD=postgres`,
      `POSTGRES_DB=${c.repo.toLowerCase()}`,
      ``
    );
  }

  if (hasRedis) {
    lines.push(
      `# ── Redis ───────────────────────────────────────────────────────────`,
      `REDIS_URL=redis://localhost:6379`,
      `REDIS_HOST=localhost`,
      `REDIS_PORT=6379`,
      ``
    );
  }

  if (hasMongo) {
    lines.push(
      `# ── MongoDB ─────────────────────────────────────────────────────────`,
      `MONGODB_URI=mongodb://localhost:27017/${c.repo.toLowerCase()}`,
      `MONGO_HOST=localhost`,
      `MONGO_PORT=27017`,
      `MONGO_DB=${c.repo.toLowerCase()}`,
      ``
    );
  }

  if (hasMysql) {
    lines.push(
      `# ── MySQL ───────────────────────────────────────────────────────────`,
      `MYSQL_URL=mysql://root:root@localhost:3306/${c.repo.toLowerCase()}`,
      `MYSQL_HOST=localhost`,
      `MYSQL_PORT=3306`,
      `MYSQL_USER=root`,
      `MYSQL_PASSWORD=root`,
      `MYSQL_DB=${c.repo.toLowerCase()}`,
      ``
    );
  }

  if (hasElastic) {
    lines.push(
      `# ── Elasticsearch ───────────────────────────────────────────────────`,
      `ELASTICSEARCH_URL=http://localhost:9200`,
      `ELASTIC_HOST=localhost`,
      `ELASTIC_PORT=9200`,
      ``
    );
  }

  lines.push(
    `# ── Feature Flags ───────────────────────────────────────────────────`,
    `# ENABLE_EXPERIMENTAL_FEATURE=false`,
    `# ENABLE_BETA_API=false`,
    ``,
    `# ── External Services ───────────────────────────────────────────────`,
    `# SMTP_HOST=smtp.example.com`,
    `# SMTP_PORT=587`,
    `# SMTP_USER=user@example.com`,
    `# SMTP_PASSWORD=your-password`,
    ``,
    `# ── Third-Party Integrations ────────────────────────────────────────`,
    `# STRIPE_SECRET_KEY=sk_test_...`,
    `# STRIPE_WEBHOOK_SECRET=whsec_...`,
    `# AWS_ACCESS_KEY_ID=...`,
    `# AWS_SECRET_ACCESS_KEY=...`,
    `# AWS_REGION=us-east-1`,
    ``
  );

  return lines.join("\n");
}
