import type { Config } from "./generator";

export function buildMakefile(c: Config): string {
  const hasPostgres = c.ports.includes("5432");
  const hasRedis = c.ports.includes("6379");

  return `# ─────────────────────────────────────────────────────────────────────
# Makefile for ${c.owner}/${c.repo}
# Generated by GHCR Devcontainer Forge
# ─────────────────────────────────────────────────────────────────────

.PHONY: help setup dev build test lint clean services logs shell

# Default target
help: ## Show this help message
\t@echo "Available commands:"
\t@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | sort | awk 'BEGIN {FS = ":.*?## "}; {printf "  \\033[36m%-15s\\033[0m %s\\n", $$1, $$2}'

# ── Setup ────────────────────────────────────────────────────────────────

setup: ## Initial project setup
\t@echo "Setting up ${c.repo}..."
\t@chmod +x setup-env.sh
\t@./setup-env.sh
\t@echo "Setup complete! Run 'make dev' to start development."

install: ## Install dependencies
\tnpm install

# ── Development ──────────────────────────────────────────────────────────

dev: ## Start development server
\tnpm run dev

start: ## Start production server
\tnpm start

# ── Build ────────────────────────────────────────────────────────────────

build: ## Build for production
\tnpm run build

preview: ## Preview production build
\tnpm run preview

# ── Testing ──────────────────────────────────────────────────────────────

test: ## Run tests
\tnpm test

test:watch: ## Run tests in watch mode
\tnpm run test:watch

test:coverage: ## Run tests with coverage
\tnpm run test:coverage

# ── Code Quality ─────────────────────────────────────────────────────────

lint: ## Run linter
\tnpm run lint

lint:fix: ## Fix linting errors
\tnpm run lint:fix

format: ## Format code
\tnpm run format

typecheck: ## Run TypeScript type checking
\tnpm run typecheck

# ── Services ─────────────────────────────────────────────────────────────

services: ## Start all services (databases, etc.)
${hasPostgres || hasRedis ? '\tdocker-compose up -d' : '\t@echo "No services configured. Add ports to enable services."'}

services:stop: ## Stop all services
\tdocker-compose down

services:logs: ## View service logs
\tdocker-compose logs -f

# ── Database ─────────────────────────────────────────────────────────────

${hasPostgres ? `db:migrate: ## Run database migrations
\tnpm run db:migrate

db:seed: ## Seed database
\tnpm run db:seed

db:reset: ## Reset database
\tnpm run db:reset
` : ''}

# ── Docker ───────────────────────────────────────────────────────────────

docker:build: ## Build Docker image
\tdocker build -t ${c.repo.toLowerCase()}:latest .

docker:run: ## Run Docker container
\tdocker run -p ${c.ports[0] || '3000'}:${c.ports[0] || '3000'} ${c.repo.toLowerCase()}:latest

docker:push: ## Push Docker image to registry
\tdocker tag ${c.repo.toLowerCase()}:latest ghcr.io/${c.owner.toLowerCase()}/${c.repo.toLowerCase()}:latest
\tdocker push ghcr.io/${c.owner.toLowerCase()}/${c.repo.toLowerCase()}:latest

# ── DevContainer ─────────────────────────────────────────────────────────

container:up: ## Start dev container
\tdevcontainer up --workspace-folder .

container:build: ## Rebuild dev container
\tdevcontainer build --workspace-folder .

container:exec: ## Execute command in container
\tdevcontainer exec --workspace-folder . $(CMD)

container:logs: ## View container logs
\tdocker logs -f $$(docker ps -q -f name=${c.repo.toLowerCase()})

# ── Cleanup ──────────────────────────────────────────────────────────────

clean: ## Clean build artifacts
\trm -rf node_modules dist .next .turbo
\t@echo "Cleaned build artifacts"

clean:all: ## Clean everything including dependencies
\tmake clean
\trm -rf package-lock.json
\t@echo "Cleaned everything"

# ── Utilities ────────────────────────────────────────────────────────────

shell: ## Open shell in dev container
\tdocker exec -it $$(docker ps -q -f name=${c.repo.toLowerCase()}) ${c.shell}

logs: ## View application logs
\ttail -f logs/*.log

env:check: ## Check environment variables
\t@test -f .env && echo "✓ .env file exists" || echo "✗ .env file missing. Copy .env.example to .env"

deps:check: ## Check for outdated dependencies
\tnpm outdated

deps:update: ## Update dependencies
\tnpm update

# ── CI/CD ────────────────────────────────────────────────────────────────

ci: ## Run CI checks locally
\t@echo "Running CI checks..."
\tmake lint
\tmake typecheck
\tmake test
\tmake build
\t@echo "✓ All CI checks passed"

# ── Documentation ────────────────────────────────────────────────────────

docs:generate: ## Generate documentation
\t@echo "Generating documentation..."
\t# Add your documentation generation command here

docs:serve: ## Serve documentation locally
\t@echo "Serving documentation..."
\t# Add your documentation server command here
`;
}
